backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "sessions"
    label: "Sessions"
    folder: "src/pages/sessions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "session"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Cover", name: "cover", widget: "string"}
      - label: "Views"
        name: "views"
        widget: "list"
        fields:
          - {label: "Type", name: "type", widget: "string" }
          - {label: "First", name: "first", widget: "string" }
          - {label: "Second", name: "second", widget: "string" }
      - label: "Info"
        name: "info"
        widget: "list"
        fields:
          - {label: "Role", name: "role", widget: "string" }
          - {label: "Name", name: "name", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
